Lightning Comes Before [Rolling Thunder Grenade]
meepen/pluto-inv pull request #87
Opened 2022-02-13 01:35 UTC by V2LenKagamine

**Please note: This PR requires the merging of https://github.com/meepen/tttrw/pull/110 !!!**

Adds The following:
- Rolling Thunder Grenade
- New Mod: Of Thunder: III-I Adds 1-3 bounces to [Rolling Thunder Grenade Only]
- New Mod: Of Spares I: Adds 1 extra grenade of the same type
- New Grenade Tiers: Stabilized(3Mod) and Explosive(4mod)

Spares works with all grenade types that extend ttt_basegrenade.
Thunder only works and can roll on a Rolling Thunder Grenade.

Tested and working as intended.

Next in Line: MIRV + Cherry + Dense + Wide

2022-02-14 19:27 UTC, meepen requested changes

2022-02-14 21:57 UTC, V2LenKagamine commented on lua/entities/pluto_rolling_thunder.lua
> +    timer.Create("thundercrack",10,1, function()
Fixed, timer gone.

2022-02-24 03:58 UTC, meepen commented
will review this over weekend

2022-02-24 03:58 UTC, meepen approved these changes

2022-10-24 08:19 UTC, V2LenKagamine commented
Time wears away will, and with it dreams.

2022-10-24 08:19 UTC, closed without merging